# Análisis de datos - Gimnasios

### 1. Lectura del archivo

In [1]:
import pandas as pd

df_gimnasio = pd.read_csv('gimnasios_entrenamiento.csv', index_col=False)
df_gimnasio.head()

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
0,SOC-10001,Medellín Poblado,Básico,Spinning,1,60.0,25000.0,Congelada
1,SOC-10002,Manizales Centro,Platino,Funcional,5,60.0,55000.0,Congelada
2,SOC-10003,Armenia Norte,VIP Total,Yoga y Pilates,14,60.0,25000.0,Activa
3,SOC-10004,Armenia Norte,Básico,Spinning,2,NaN,25000.0,Congelada
4,SOC-10005,Chinchiná,VIP Total,Yoga y Pilates,26,NaN,95000.0,Activa

### 2. Selección de columnas

In [2]:
disciplina = df_gimnasio['Disciplina_Principal']
print(type(disciplina))

tabla_reducida = df_gimnasio[['Sede', 'Plan', 'Visitas_Mes']]
tabla_reducida.head()

<class 'pandas.Series'>

               Sede       Plan  Visitas_Mes
0  Medellín Poblado     Básico            1
1  Manizales Centro    Platino            5
2     Armenia Norte  VIP Total           14
3     Armenia Norte     Básico            2
4         Chinchiná  VIP Total           26

### 3. loc

In [3]:
df_gimnasio.loc[350]

ID_Socio                       SOC-10351
Sede                       Armenia Norte
Plan                             Platino
Disciplina_Principal           Funcional
Visitas_Mes                           17
Minutos_Promedio_Sesion             75.0
Gasto_Suplementos                    NaN
Estado_Membresia                  Activa
Name: 350, dtype: object

### 4. Duplicados

In [4]:
print(df_gimnasio.duplicated().sum())
df_gimnasio = df_gimnasio.drop_duplicates()
print(df_gimnasio.shape)

12
(1000, 8)

### 5. Visitas mayores a 18

In [5]:
df_gimnasio[df_gimnasio['Visitas_Mes'] > 18]

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
4,SOC-10005,Chinchiná,VIP Total,Yoga y Pilates,26,NaN,95000.0,Activa
5,SOC-10006,Armenia Norte,Básico,Yoga y Pilates,25,45.0,0.0,Activa
8,SOC-10009,Pereira Circunvalar,Platino,Crossfit,21,NaN,NaN,Activa
11,SOC-10012,Manizales Centro,Básico,Yoga y Pilates,21,60.0,NaN,Activa
14,SOC-10015,Manizales Centro,VIP Total,Funcional,27,45.0,0.0,Activa
...,...,...,...,...,...,...,...,...
987,SOC-10988,Armenia Norte,Platino,Spinning,19,45.0,55000.0,Activa
991,SOC-10992,Pereira Circunvalar,Platino,Funcional,23,60.0,55000.0,Activa
993,SOC-10994,Medellín Poblado,Platino,Crossfit,21,60.0,95000.0,Activa
994,SOC-10995,Medellín Poblado,Platino,Yoga y Pilates,21,45.0,0.0,Activa
999,SOC-11000,Pereira Circunvalar,Platino,Yoga y Pilates,22,45.0,55000.0,Activa

### 6. isin

In [6]:
df_gimnasio[df_gimnasio['Plan'].isin(['VIP Total', 'Platino'])]

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
1,SOC-10002,Manizales Centro,Platino,Funcional,5,60.0,55000.0,Congelada
2,SOC-10003,Armenia Norte,VIP Total,Yoga y Pilates,14,60.0,25000.0,Activa
4,SOC-10005,Chinchiná,VIP Total,Yoga y Pilates,26,NaN,95000.0,Activa
7,SOC-10008,Armenia Norte,VIP Total,Yoga y Pilates,12,35.0,0.0,Activa
8,SOC-10009,Pereira Circunvalar,Platino,Crossfit,21,NaN,NaN,Activa
...,...,...,...,...,...,...,...,...
993,SOC-10994,Medellín Poblado,Platino,Crossfit,21,60.0,95000.0,Activa
994,SOC-10995,Medellín Poblado,Platino,Yoga y Pilates,21,45.0,0.0,Activa
996,SOC-10997,Medellín Poblado,VIP Total,Crossfit,1,NaN,140000.0,Activa
997,SOC-10998,Armenia Norte,VIP Total,Crossfit,4,75.0,0.0,Activa
999,SOC-11000,Pereira Circunvalar,Platino,Yoga y Pilates,22,45.0,55000.0,Activa

### 7. between

In [7]:
df_gimnasio[df_gimnasio['Minutos_Promedio_Sesion'].between(45.0, 75.0)]

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
0,SOC-10001,Medellín Poblado,Básico,Spinning,1,60.0,25000.0,Congelada
1,SOC-10002,Manizales Centro,Platino,Funcional,5,60.0,55000.0,Congelada
2,SOC-10003,Armenia Norte,VIP Total,Yoga y Pilates,14,60.0,25000.0,Activa
5,SOC-10006,Armenia Norte,Básico,Yoga y Pilates,25,45.0,0.0,Activa
6,SOC-10007,Medellín Poblado,Estudiantil,Spinning,18,60.0,0.0,Activa
...,...,...,...,...,...,...,...,...
994,SOC-10995,Medellín Poblado,Platino,Yoga y Pilates,21,45.0,0.0,Activa
995,SOC-10996,Medellín Poblado,Básico,Musculación,17,75.0,0.0,Vencida
997,SOC-10998,Armenia Norte,VIP Total,Crossfit,4,75.0,0.0,Activa
998,SOC-10999,Medellín Poblado,Estudiantil,Yoga y Pilates,8,75.0,25000.0,Activa
999,SOC-11000,Pereira Circunvalar,Platino,Yoga y Pilates,22,45.0,55000.0,Activa

### 8. query

In [8]:
df_gimnasio.query('Sede == "Medellín Poblado" and Estado_Membresia == "Activa"')

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
6,SOC-10007,Medellín Poblado,Estudiantil,Spinning,18,60.0,0.0,Activa
24,SOC-10025,Medellín Poblado,Platino,Musculación,6,45.0,55000.0,Activa
25,SOC-10026,Medellín Poblado,Básico,Spinning,15,45.0,220000.0,Activa
59,SOC-10060,Medellín Poblado,Platino,Crossfit,12,35.0,55000.0,Activa
75,SOC-10076,Medellín Poblado,Platino,Yoga y Pilates,20,45.0,NaN,Activa
...,...,...,...,...,...,...,...,...
986,SOC-10987,Medellín Poblado,Platino,Musculación,19,90.0,0.0,Activa
993,SOC-10994,Medellín Poblado,Platino,Crossfit,21,60.0,95000.0,Activa
994,SOC-10995,Medellín Poblado,Platino,Yoga y Pilates,21,45.0,0.0,Activa
996,SOC-10997,Medellín Poblado,VIP Total,Crossfit,1,NaN,140000.0,Activa
998,SOC-10999,Medellín Poblado,Estudiantil,Yoga y Pilates,8,75.0,25000.0,Activa

### 9. Filtro con texto

In [9]:
df_gimnasio[df_gimnasio['Sede'].str.startswith('Manizales') & (df_gimnasio['Gasto_Suplementos'] > 50000)]

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia
1,SOC-10002,Manizales Centro,Platino,Funcional,5,60.0,55000.0,Congelada
42,SOC-10043,Manizales Centro,Platino,Funcional,8,60.0,55000.0,Vencida
45,SOC-10046,Manizales Centro,Estudiantil,Funcional,19,NaN,55000.0,Activa
47,SOC-10048,Manizales Centro,Estudiantil,Yoga y Pilates,26,90.0,95000.0,Vencida
55,SOC-10056,Manizales Centro,Básico,Musculación,12,45.0,55000.0,Activa
...,...,...,...,...,...,...,...,...
938,SOC-10939,Manizales Centro,Básico,Yoga y Pilates,27,75.0,140000.0,Vencida
941,SOC-10942,Manizales Centro,Platino,Crossfit,28,60.0,55000.0,Activa
960,SOC-10961,Manizales Centro,Platino,Spinning,24,45.0,95000.0,Activa
972,SOC-10973,Manizales Centro,Básico,Yoga y Pilates,28,60.0,95000.0,Congelada
984,SOC-10985,Manizales Centro,VIP Total,Spinning,6,45.0,55000.0,Activa

### 10. Valores faltantes

In [10]:
print(df_gimnasio.isna().sum())

promedio = df_gimnasio['Minutos_Promedio_Sesion'].mean()
df_gimnasio['Minutos_Promedio_Sesion'] = df_gimnasio['Minutos_Promedio_Sesion'].fillna(promedio)
df_gimnasio['Gasto_Suplementos'] = df_gimnasio['Gasto_Suplementos'].fillna(0.0)

print(df_gimnasio.isna().sum())

ID_Socio                    0
Sede                        0
Plan                        0
Disciplina_Principal        0
Visitas_Mes                 0
Minutos_Promedio_Sesion    56
Gasto_Suplementos          57
Estado_Membresia            0
dtype: int64
ID_Socio                   0
Sede                       0
Plan                       0
Disciplina_Principal       0
Visitas_Mes                0
Minutos_Promedio_Sesion    0
Gasto_Suplementos          0
Estado_Membresia           0
dtype: int64

### 11. apply

In [11]:
def perfil(visitas):
    if visitas < 8:
        return 'Esporádico'
    elif visitas <= 16:
        return 'Regular'
    else:
        return 'Frecuente'

df_gimnasio['Perfil_Atleta'] = df_gimnasio['Visitas_Mes'].apply(perfil)
df_gimnasio.head()

,ID_Socio,Sede,Plan,Disciplina_Principal,Visitas_Mes,Minutos_Promedio_Sesion,Gasto_Suplementos,Estado_Membresia,Perfil_Atleta
0,SOC-10001,Medellín Poblado,Básico,Spinning,1,60.000000,25000.0,Congelada,Esporádico
1,SOC-10002,Manizales Centro,Platino,Funcional,5,60.000000,55000.0,Congelada,Esporádico
2,SOC-10003,Armenia Norte,VIP Total,Yoga y Pilates,14,60.000000,25000.0,Activa,Regular
3,SOC-10004,Armenia Norte,Básico,Spinning,2,60.752119,25000.0,Congelada,Esporádico
4,SOC-10005,Chinchiná,VIP Total,Yoga y Pilates,26,60.752119,95000.0,Activa,Frecuente

### 12. rename y orden de columnas

In [12]:
df_gimnasio = df_gimnasio.rename(columns={'Minutos_Promedio_Sesion': 'Duracion_Media', 'Disciplina_Principal': 'Deporte'})

df_gimnasio = df_gimnasio[['ID_Socio', 'Perfil_Atleta', 'Sede', 'Plan', 'Deporte', 'Visitas_Mes', 'Duracion_Media', 'Gasto_Suplementos', 'Estado_Membresia']]
df_gimnasio.head()

,ID_Socio,Perfil_Atleta,Sede,Plan,Deporte,Visitas_Mes,Duracion_Media,Gasto_Suplementos,Estado_Membresia
0,SOC-10001,Esporádico,Medellín Poblado,Básico,Spinning,1,60.000000,25000.0,Congelada
1,SOC-10002,Esporádico,Manizales Centro,Platino,Funcional,5,60.000000,55000.0,Congelada
2,SOC-10003,Regular,Armenia Norte,VIP Total,Yoga y Pilates,14,60.000000,25000.0,Activa
3,SOC-10004,Esporádico,Armenia Norte,Básico,Spinning,2,60.752119,25000.0,Congelada
4,SOC-10005,Frecuente,Chinchiná,VIP Total,Yoga y Pilates,26,60.752119,95000.0,Activa

### 13. Agregación por sede

In [13]:
df_gimnasio.groupby('Sede').agg({'Duracion_Media': 'mean', 'Gasto_Suplementos': 'sum'})

                     Duracion_Media  Gasto_Suplementos
Sede
Armenia Norte             61.511178          9990000.0
Chinchiná                 60.330008         11455000.0
Manizales Centro          59.253738          9600000.0
Medellín Poblado          62.115406          8910000.0
Pereira Circunvalar       60.672316          7605000.0

### 14. Rango por plan

In [14]:
def rango(series):
    return series.max() - series.min()

df_gimnasio.groupby('Plan')[['Visitas_Mes', 'Duracion_Media']].agg(rango)

             Visitas_Mes  Duracion_Media
Plan
Básico                27            75.0
Estudiantil           27            75.0
Platino               27            75.0
VIP Total             27            75.0

### 15. Sede y plan

In [15]:
df_gimnasio.groupby(['Sede', 'Plan']).agg({'Visitas_Mes': 'mean', 'Gasto_Suplementos': 'sum'})

                                 Visitas_Mes  Gasto_Suplementos
Sede                Plan
Armenia Norte       Básico         14.400000          3525000.0
                    Estudiantil    14.131579          1940000.0
                    Platino        11.746032          3635000.0
                    VIP Total      13.875000           890000.0
Chinchiná           Básico         14.679012          5070000.0
                    Estudiantil    12.324324          1615000.0
                    Platino        14.700000          3505000.0
                    VIP Total      15.678571          1265000.0
Manizales Centro    Básico         13.608696          3010000.0
                    Estudiantil    16.547619          2110000.0
                    Platino        13.741935          2940000.0
                    VIP Total      13.257143          1540000.0
Medellín Poblado    Básico         15.175676          3810000.0
                    Estudiantil    12.888889          1315000.0
                    Platino        14.771930          2340000.0
                    VIP Total      12.307692          1445000.0
Pereira Circunvalar Básico         14.400000          3060000.0
                    Estudiantil    12.944444          1530000.0
                    Platino        14.016393          2240000.0
                    VIP Total      12.478261           775000.0